name: audit

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit_ci:
    runs-on: ubuntu-latest
    name: JS
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Setup audit-ci
        run: npm install -g audit-ci

      - name: Audit NPM dependencies
        run: audit-ci --medium
